### ISSUE TITLE
PG cluster extending issue caused by partitioned table by hash

### ISSUE THREAD

**Issue by cailin-lai** [postgrespro/shardman#3]
Hi @danolivo ,
Although it may not be good to ask this question here, it's really an issue for me. I know this issue actually comes from the FDW + partition table by hash methodologies, after I looking into the details of shardman, it looks has similar maintenance issue.  
Let me describe my scenario here,
My goal is to have a kinds of master-less pg cluster, and it will be easy to be horizontal extended. With FDW + partition, ideally, any single-node can ingest data (forward data to desired nodes by fdw); any single-node can perform all data queries,(append/aggr data from all nodes by fdw).
Initially, I've 2 servers, and the data are distributed into 2 server by hash(user_id), in this case, we can insure that the data for one user_id can be located to only one server. e.g. 1000 goes to server A, 1001 goes to server B... this works pretty well.
In case of I need to add one new server node to extend the PG cluster, so, the mod value needs to be updated. That means, the historical data will be still kept in original nodes, and new data will go to nodes by new rule. In this case, the manual re-balance data by moving data between nodes would be tricky. Specifically,  the tuples are big (e.g. billion tuples).
Is there a way that can keep the original rule not be updated, and new data will follow the original rule from PG internals. e.g. an much straightforward extension?

*The reason why one unique User ID needs to be in one node,  it's to save the costs for the frequent business data queries. The costs are heavy in case of the detailed list data needs to be pulled from all nodes.

Thanks to Team!

Allen

**Comment by danolivo** [comment]
Thank you for the interesting question.
This is not possible on the the working production system. But You can reorganize the sharding scheme for future server additions. You need:

* to add into relation the partition schema revision column that be set by DEFAULT on INSERT (maybe on UPDATE/DELETE too, if it will be optimal for your your business logic).
* to introduce two levels of partitioning: 1 - by the schema revision; 2 - by hash(user_id).

It is maybe strange solution, but it works good in the case if you don't worried about optimization of complex queries.

Example:

`DROP TABLE IF EXISTS test CASCADE;

CREATE TABLE test (
	schema_rev smallint DEFAULT 0, -- Maybe here we can use CHAR, 1-byte type for reduce the size of relation?
	user_id int,
	payload TEXT
) PARTITION BY LIST(schema_rev);

CREATE TABLE test_0 PARTITION OF test (schema_rev) FOR VALUES IN (0) PARTITION BY HASH (user_id);
CREATE TABLE test_0_0 PARTITION OF test_0 (user_id) FOR VALUES WITH (modulus 2, remainder 0);
CREATE TABLE test_0_1 PARTITION OF test_0 (user_id) FOR VALUES WITH (modulus 2, remainder 1);

-- Fill partitioned table
INSERT INTO test (user_id, payload) SELECT gs.* , 'data' || gs.* FROM generate_series(1,100) AS gs;

-- Check data
SELECT * FROM
	(SELECT count(*) AS overall FROM test) AS a,
	(SELECT count(*) AS t0_0 FROM test_0_0) AS b,
	(SELECT count(*) AS t0_1 FROM test_0_1) AS c;

-- Add new server, new partition schema:
CREATE TABLE test_1 PARTITION OF test (schema_rev) FOR VALUES IN (1) PARTITION BY HASH (user_id);
CREATE TABLE test_1_0 PARTITION OF test_1 (user_id) FOR VALUES WITH (modulus 3, remainder 0);
CREATE TABLE test_1_1 PARTITION OF test_1 (user_id) FOR VALUES WITH (modulus 3, remainder 1);
CREATE TABLE test_1_2 PARTITION OF test_1 (user_id) FOR VALUES WITH (modulus 3, remainder 2);

-- Set new DEFAULT revision
ALTER TABLE test ALTER COLUMN schema_rev SET DEFAULT 1; 

-- Add to partitioned table
INSERT INTO test (user_id, payload) SELECT gs.* , 'data' || gs.* FROM generate_series(1,100) AS gs;

-- Check that additions routed into new schema
SELECT * FROM
	(SELECT count(*) AS overall FROM test) AS a,
	(SELECT count(*) AS t0 FROM test_0) AS b,
	(SELECT count(*) AS t1 FROM test_1) AS c,
	(SELECT count(*) AS t1_0 FROM test_1_0) AS d,
	(SELECT count(*) AS t1_1 FROM test_1_1) AS e,
	(SELECT count(*) AS t1_2 FROM test_1_2) AS f;
`

**Comment by cailin-lai** [comment]
Thank you so much @danolivo !
Yep, it actually depends on the application(s) can recognize the business data belongs to which revision, and keep the value in SQL request. With this contract, the existing data will be still navigated to original server. Very nice!
The data solution indeed requires 2 levels partition, since the data is time-series, the 2nd will be time range. We do need to balance the data ingestion speed(~20k/s) and data usage, e.g. Aggregation reports(not care much to get data from multi-servers since the aggr pushdown is very well.) and details list(it's necessary to pull full rows data from less servers).
Anyway, the details above are good enough for me.  I'd close the ticket.

Appreciate for help!

Allen

**Comment by danolivo** [comment]
Thank you too!
My team and I are currently working hard on the sharding features of PostgreSQL for vanilla and enterprise editions. We are very interested in any sharding use cases for developing the features in the right way.
You can affect and speedup sharding development if you can describe for us (maybe in private email) your opinion on sharding, describe any problems or needs, describe software environment and so on.
We are also looking for test databases and sample queries, to form an benchmark.

**Comment by cailin-lai** [comment]
Sure! I'd have detailed document for data scenario and desired architecture, will be ready for you by email in the early of next week.
Thanks!
